const state = { reports: [], editingId: null, user: null };
const $ = selector => document.querySelector(selector);
const dialog = $('#reportDialog');
const form = $('#reportForm');
const loginScreen = $('#loginScreen');
const loginForm = $('#loginForm');
const thaiMonths = ['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'];
const dateText = date => { const d = new Date(`${date}T00:00:00`); return { day: String(d.getDate()).padStart(2, '0'), month: thaiMonths[d.getMonth()], full: d.toLocaleDateString('th-TH', { day:'numeric', month:'long', year:'numeric' }) }; };
const escapeHtml = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
function render() {
  const query = $('#searchInput').value.toLowerCase(); const status = $('#statusFilter').value;
  const reports = state.reports.filter(r => (!query || `${r.project} ${r.location} ${r.workDone}`.toLowerCase().includes(query)) && (status === 'all' || r.status === status));
  $('#totalMetric').textContent = state.reports.length; $('#progressMetric').textContent = state.reports.filter(r => r.status === 'in-progress').length; $('#completeMetric').textContent = state.reports.filter(r => r.status === 'completed').length;
  const today = new Date().toISOString().slice(0,10); $('#peopleMetric').innerHTML = `${state.reports.filter(r => r.date === today).reduce((sum, r) => sum + Number(r.manpower || 0), 0)} <small>คน</small>`;
  $('#reportList').innerHTML = reports.length ? reports.map(r => { const d = dateText(r.date); const deleteButton = state.user?.role === 'admin' ? `<button class="delete-button" type="button" data-delete-id="${r.id}" title="ลบรายงาน" aria-label="ลบรายงาน">×</button>` : ''; return `<article class="report-card"><div class="report-date"><strong>${d.day}</strong><span>${d.month} ${new Date(`${r.date}T00:00:00`).getFullYear()+543}</span></div><div class="report-info"><h3>${escapeHtml(r.project)}</h3><p>${escapeHtml(r.workDone)}</p><small>${escapeHtml(r.location || 'ไม่ได้ระบุสถานที่')} · ${escapeHtml(r.supervisor)}</small></div><div class="report-side"><span class="badge ${r.status}">${r.status === 'completed' ? 'เสร็จสิ้น' : r.status === 'planned' ? 'วางแผน' : 'กำลังดำเนินการ'}</span><div class="bar"><i style="width:${Math.min(100, Number(r.progress)||0)}%"></i></div><strong>${Number(r.progress)||0}%</strong>${deleteButton}</div></article>`; }).join('') : '<div class="empty">ไม่พบรายงานที่ตรงกับเงื่อนไข</div>';
}
async function loadReports() { const response = await fetch('/api/reports'); if (response.status === 401) return showLogin(); state.reports = await response.json(); render(); }
function showLogin() { loginScreen.classList.remove('hidden'); document.querySelector('.app-shell').classList.add('locked'); }
function showApp(user) { state.user = user; loginScreen.classList.add('hidden'); document.querySelector('.app-shell').classList.remove('locked'); $('#currentUserName').textContent = user.displayName; render(); }
function openForm(report) { state.editingId = report?.id || null; $('#formTitle').textContent = report ? 'แก้ไขรายงานประจำวัน' : 'สร้างรายงานประจำวัน'; form.reset(); form.date.value = report?.date || new Date().toISOString().slice(0,10); if (report) Object.keys(report).forEach(key => { if (form[key]) form[key].value = report[key]; }); dialog.showModal(); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2500); }
form.addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); data.progress = Number(data.progress); data.manpower = Number(data.manpower); const endpoint = state.editingId ? `/api/reports/${state.editingId}` : '/api/reports'; const response = await fetch(endpoint, { method: state.editingId ? 'PATCH' : 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(data) }); if (!response.ok) { const error = await response.json(); return toast(error.error || 'บันทึกไม่สำเร็จ'); } dialog.close(); await loadReports(); toast(state.editingId ? 'อัปเดตรายงานแล้ว' : 'บันทึกรายงานแล้ว'); });
$('#newReportBtn').addEventListener('click', () => openForm());
$('#exportBtn').addEventListener('click', () => window.print());
$('#logoutBtn').addEventListener('click', async () => { if (!window.confirm('ต้องการออกจากระบบหรือไม่?')) return; await fetch('/api/auth/logout', { method: 'POST' }); showLogin(); loginForm.reset(); });
$('#reportList').addEventListener('click', async event => { const button = event.target.closest('[data-delete-id]'); if (!button) return; const report = state.reports.find(item => item.id === button.dataset.deleteId); if (!report || !window.confirm(`ต้องการลบรายงานโครงการ ${report.project} หรือไม่?`)) return; const response = await fetch(`/api/reports/${report.id}`, { method: 'DELETE' }); if (!response.ok) return toast('ลบรายงานไม่สำเร็จ'); await loadReports(); toast('ลบรายงานแล้ว'); });
loginForm.addEventListener('submit', async event => { event.preventDefault(); const response = await fetch('/api/auth/login', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(Object.fromEntries(new FormData(loginForm))) }); if (!response.ok) { const error = await response.json(); $('#loginError').textContent = error.error; return; } const result = await response.json(); $('#loginError').textContent = ''; showApp(result.user); await loadReports(); });
$('#closeDialog').addEventListener('click', () => dialog.close()); $('#cancelBtn').addEventListener('click', () => dialog.close()); $('#searchInput').addEventListener('input', render); $('#statusFilter').addEventListener('change', render); $('#todayLabel').textContent = dateText(new Date().toISOString().slice(0,10)).full;
fetch('/api/auth/me').then(response => response.json()).then(result => { if (result.user) { showApp(result.user); loadReports(); } else showLogin(); });
